### ISSUE TITLE
BUG: Side Navbar Menu Icon Persistence

### ISSUE THREAD

**Issue by Amruta7203** [EternoSeeker/gameoflife#137] opened 2024-05-26 15:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The three horizontal lines menu icon (hamburger menu) in the side navbar remains visible even after the navbar is opened. This behavior is visually confusing because the icon typically signifies a closed menu.

<img width="965" alt="img" src="https://github.com/EternoSeeker/gameoflife/assets/116087736/77bb0f5a-1338-4539-a4c2-feac8b44c884">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment] 2024-05-30 12:46
@Amruta7203 in PR #161 the problem is addressed, if you still find any issue with the sidebar, please suggest, thank you.

**Comment by Amruta7203** [comment] 2024-05-30 13:18
@EternoSeeker The issue associated with this PR #161 was raised much later (#150). It should have been marked as duplicate right?

**Comment by EternoSeeker** [comment] 2024-05-30 16:09
> @EternoSeeker The issue associated with this PR #161 was raised much later (#150). It should have been marked as duplicate right?

They made it responsive for smaller devices, and in that process closing of the icon was addressed as well.
I think there are still lot of minor things which can be made better, if you have ideas please tell, thank you.

**Comment by Amruta7203** [comment] 2024-06-01 09:32
Ok @EternoSeeker I have another issue to raise regarding the hover effects of the theme types. It is not consistent. I would like to work on the same.

**Comment by EternoSeeker** [comment] 2024-06-01 13:20
Okay

**Closed** 2024-06-02 16:25 UTC
Labels: bug, gssoc, level1
